### ISSUE TITLE
U+25CC DOTTED CIRCLE’s anchor point is misplaced

### ISSUE THREAD

**Issue by dscorbett** [notofonts/mende-kikakui#1]
### Font
NotoSansMendeKikakui-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/mende-kikakui/releases/tag/NotoSansMendeKikakui-v2.003
Date: 2022-08-29

### Font version
Version 2.003

### Issue
U+25CC DOTTED CIRCLE’s anchor point is too high and too far to the right.

### Character data
<span dir="ltr"><span dir="rtl">◌𞣕</span></span>
U+25CC DOTTED CIRCLE
U+1E8D5 MENDE KIKAKUI COMBINING NUMBER HUNDRED THOUSANDS

### Screenshot
![◌𞣕](https://user-images.githubusercontent.com/1124347/187267176-11e4d877-99d6-41fd-84aa-c61e51f4e9b3.png)

**Comment by simoncozens** [comment]
Yeah. I noticed this when building it and noticed it looked weird, but the dotted circle anchors are generated automatically so I trusted them... I'll fix it next time around.
